export const PROGRESS_CONFIG = {
  SLOW_PHASE_END: 90,
  SLOW_INCREMENT: 0.1,
  SLOW_INTERVAL: 122,
  FAST_PHASE_END: 100,
  FAST_INCREMENT: 1,
  FAST_INTERVAL: 100,
  TOTAL_TIME: 120000,
} as const;
