name: CI/CD Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip ci]'))
    runs-on: ubuntu-latest # 24.04(Ubuntu LTS)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project with Vite
        id: build
        run: pnpm run build
        continue-on-error: true

      - name: Evaluate build status
        id: status
        run: |
          result="failed"
          message="빌드 실패 ❌"

          if [ "${{ steps.build.outcome }}" == "success" ]; then
            result="success"
            message="빌드 성공 🎊"
          fi

          echo "result=$result" >> $GITHUB_OUTPUT
          echo "message=$message" >> $GITHUB_OUTPUT

      - name: Add comment to PR with build status
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const message = `${{ steps.status.outputs.message }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: `### 빌드 결과\n${message}`
            });

      - name: Fail job if build failed
        if: steps.build.outcome == 'failure'
        run: exit 1
